parameters:
#    siplec_cd.example.class: Penderie\DefaultBundle\Example

services:
#    siplec_cd.example:
#        class: %siplec_cd.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]