<?php

namespace Siplec\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Retourne les utilisateurs pour la requete ajax necessaire à jqgrid trier selon la colonne
     *
     * @return array The entities.
     */
    public function getNbResultats(array $criteria, array $orderBy = null)
    {
    	$result = $this->getEntityManager()
    	->createQuery(
    			'SELECT COUNT(u.id) nb
    			FROM SiplecUserBundle:User u 
    			ORDER BY u.id'
    	)
    	->getOneOrNullResult();
    	return $result['nb'];
    }
    
    /**
     * Retourne les utilisateurs pour la requete ajax necessaire à jqgrid trier selon la colonne
     *
     * @return array The entities.
     */
    public function getSearch(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return $this->findBy($criteria, $orderBy, $limit, $offset-1);
    }
}
