<?php

namespace Penderie\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveRepository extends EntityRepository
{
	/**
	 * TODO : Libere cette place d'archive en mettant le numDossier à NULL et libre à true
	 */
	public function libere() {
	}

	/**
	 * Retourne la première archive libre
	 */
	public function getFirstLineLibre(){
		$query = $this->createQueryBuilder('u')
			->where("u.libre = 1")
			->orderBy("u.id", "ASC")
			->setMaxResults(1);
			
		return $query->getQuery()->getOneOrNullResult();
	}
}
