<?php

namespace Penderie\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutDossierRepository extends EntityRepository
{
	
	/**
	 * Pour l'affichage d'un select sur la deuxieme étape du traitement de l'opérateur
	 * 
	 * @return QueryBuilder.
	 */
	public function getRequeteStatutTraitementSecondEtape()
	{
		$repository = $this->getEntityManager()->getRepository('PenderieDefaultBundle:StatutDossier');
		return $repository->createQueryBuilder('s')
		->where('s.id IN (:statut)')
		->orderBy('s.id','ASC')
		->setParameter('statut', array(Dossier::STATUT_VALIDE,Dossier::STATUT_REFUSE,Dossier::STATUT_INCOMPLET));
	}
}
